/*
 * This source file was generated by the Gradle 'init' task
 */
package bcc.textDecisionGame;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;

public class App {
    public static void main(String[] args) {
        JFrame frame = new JFrame("Swing Layout Example");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(800, 300);
        // Use BorderLayout
        frame.setLayout(new BorderLayout());
        JTextArea text = new JTextArea("A wildfire has started, which team will you deploy as?");
        text.setLineWrap(true);

        frame.add(text, BorderLayout.CENTER);

        // Create panel for buttons at bottom
        JPanel buttonPanel = new JPanel(new BorderLayout());

        JButton leftButton = new JButton("Firefighters");
        JButton rightButton = new JButton("Dozer Crew");
        //frame.

        // Set up game end helper
        endOptions endGame = new endOptions(text, leftButton, rightButton);
        
        leftButton.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                if (text.getText().equals("A wildfire has started, which team will you deploy as?")){
                    text.setText("You've reached the fire, what should you do next?");
                    leftButton.setText("Start spraying the fire with water");
                    rightButton.setText("Start making a fireline to contain the fire");
                }
                else if (text.getText().equals("You've reached the fire, what should you do next?")){
                    text.setText("You're running out of water, what should you do?");
                    leftButton.setText("Retreat to a water supply source");
                    rightButton.setText("Request refill from a tanker");
                }
                else if (text.getText().equals("You're running out of water, what should you do?")){
                    text.setText("You retreated to a water supply source, and while you were gone the fire was contained and burned out.  Not a bad ending but the other players are angry that you sprayed water like a newbie instead of helping them contain the fire.");
                    endGame.endingButtons();
                }
                else if (text.getText().equals("Where do you put the branches from your fireline?")){
                    text.setText("You left the flammable branches in the line, making the line useless and letting the fire jump the line.  Everyone hates you for letting the fire escape containment.");
                    endGame.endingButtons();
                }
                else if (text.getText().equals("Which dozer should you use?")){
                    text.setText("You've reached the fire, where should you make a line?");
                    leftButton.setText("Make a line near the fire to stop the spread");
                    rightButton.setText("Make a line a little far from the fire");
                }
                else if (text.getText().equals("You've reached the fire, where should you make a line?")){
                    text.setText("The fire was spreading too quickly, your dozer was surrounded by fire and burned down.  Pretty bad ending.");
                    endGame.endingButtons();
                }
                else if (text.getText().equals("You've reached the fire, should you start making a line or wait for the woodchipper truck to arrive?")){
                    text.setText("You started using a heavy dozer which, by the way, cuts down trees and leaves branches, without a team ready to deal with the branches.  Your fireline was useless and allowed the fire to jump.  Everyone hates you for letting the fire escape containment.");
                    endGame.endingButtons();
                }
                else if (leftButton.getText().equals("RESTART")){
                    endGame.restart();
                }
            }
        });

        rightButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (text.getText().equals("You're running out of water, what should you do?")){
                    text.setText("You were refilled by a tanker, but because of that the tanker took longer to refill a helicopter which could have helped contain the fire.  You took time and resources while contributing very little.  People don't really like you for that.");
                    endGame.endingButtons();
                }
                else if (text.getText().equals("You've reached the fire, what should you do next?")){
                    text.setText("Where do you put the branches from your fireline?");
                    leftButton.setText("Leave them where they are");
                    rightButton.setText("Throw them into the fire");
                }
                else if (text.getText().equals("Where do you put the branches from your fireline?")){
                    text.setText("You threw the branches into the fire, preventing them from compromising the fireline and allowing you and your teammates to succesfully contain the fire.");
                    endGame.endingButtons();
                }
                else if (text.getText().equals("A wildfire has started, which team will you deploy as?")){
                    text.setText("Which dozer should you use?");
                    leftButton.setText("Light dozer, does not cut down trees");
                    rightButton.setText("Heavy dozer, does cut down trees");
                }
                else if (text.getText().equals("You've reached the fire, where should you make a line?")){
                    text.setText("You succesfully made a line without risking your dozer or your life.  Everyone likes you for making a proper line and helping to contain the fire.");
                    endGame.endingButtons();
                }
                else if (text.getText().equals("Which dozer should you use?")){
                    text.setText("You've reached the fire, should you start making a line or wait for the woodchipper truck to arrive?");
                    leftButton.setText("Start making a line");
                    rightButton.setText("Wait for woodchipper truck");
                }
                else if (text.getText().equals("You've reached the fire, should you start making a line or wait for the woodchipper truck to arrive?")){
                    text.setText("You waited for the woodchipper truck before starting your line.  While making your line, the woodchipper truck followed behind and cleaned up all the branches, allowing you to quickly and effectively make a fireline and contain the fire.  Everyone likes you for the hard work and good decisions you made to contain the fire as quickly as possible!");
                    endGame.endingButtons();
                }
                else if (rightButton.getText().equals("END")){
                    frame.dispose();
                }
            }
    });

        buttonPanel.add(leftButton, BorderLayout.WEST);
        buttonPanel.add(rightButton, BorderLayout.EAST);

        frame.add(buttonPanel, BorderLayout.SOUTH);

        // Show frame
        frame.setVisible(true);
    }
}
